ping -c 3 ap-southeast-2.ec2.cloudharmony.net
ping -c 3 australia-southeast1.gce.cloudharmony.net
ping -c 3 australia-east.azure.cloudharmony.net
ping -c 3 sa-east-1.ec2.cloudharmony.net
ping -c 3 southamerica-east1.gce.cloudharmony.net
ping -c 3 brazil-south.azure.cloudharmony.net
ping -c 3 ca-central-1.ec2.cloudharmony.net
ping -c 3 northamerica-northeast1.gce.cloudharmony.net
ping -c 3 canada-central.azure.cloudharmony.net
ping -c 3 eu-central-1.ec2.cloudharmony.net
ping -c 3 europe-west3.gce.cloudharmony.net
ping -c 3 germany-westcentral.azure.cloudharmony.net
ping -c 3 eu-west-2.ec2.cloudharmony.net
ping -c 3 europe-west2.gce.cloudharmony.net
ping -c 3 uk-south.azure.cloudharmony.net
ping -c 3 ap-east-1.ec2.cloudharmony.net
ping -c 3 asia-east2.gce.cloudharmony.net
ping -c 3 asia-east.azure.cloudharmony.net
ping -c 3 ap-south-1.ec2.cloudharmony.net
ping -c 3 asia-south1.gce.cloudharmony.net
ping -c 3 india-west.azure.cloudharmony.net
ping -c 3 ap-northeast-1.ec2.cloudharmony.net
ping -c 3 asia-northeast1.gce.cloudharmony.net
ping -c 3 japan-east.azure.cloudharmony.net
ping -c 3 ap-northeast-2.ec2.cloudharmony.net
ping -c 3 asia-northeast3.gce.cloudharmony.net
ping -c 3 korea-central.azure.cloudharmony.net
ping -c 3 ap-southeast-1.ec2.cloudharmony.net
ping -c 3 asia-southeast1.gce.cloudharmony.net
ping -c 3 asia-southeast.azure.cloudharmony.net
ping -c 3 us-west2-a.gce.cloudharmony.net
ping -c 3 us-west-1.ec2.cloudharmony.net
ping -c 3 us-west.azure.cloudharmony.net
ping -c 3 us-east.azure.cloudharmony.net
ping -c 3 us-east4.gce.cloudharmony.net
ping -c 3 us-east-1.ec2.cloudharmony.net
